### ISSUE TITLE
god save the queen

### ISSUE THREAD

**Issue by node3112** [NathanW-05/god-bless-america-archive#1]
FUCK america

**Comment by NathanW-05** [comment]
Imagine living in a monarchy in 2022 smh

Saw const flag on r/place while scanning the top corner lmfao. Checked sub, phantom wildin with his elytras fr

**Comment by node3112** [comment]
yeah phantom 100% only enabled elytras for the r/place logo

**Comment by NathanW-05** [comment]
😍😍🙏🙏 thank you phantom 🥝🥝

😱finally helping the commuinity😇😇🥺

Any of yous try elytra packet

**Comment by NathanW-05** [comment]
Whiops didnt mean to close issue

**Comment by NathanW-05** [comment]
Whoops didnt mean to close, this very important issue

**Comment by node3112** [comment]
yes very

**Comment by node3112** [comment]
elytra packet doesn't work

**Comment by NathanW-05** [comment]
Lmao thats no fun, at least the delusional retards like oremonger are happy

**Comment by NathanW-05** [comment]
![Uploading Screenshot_20220405-082025_Reddit.jpg…]()

**Comment by NathanW-05** [comment]
![Screenshot_20220405-082025_Reddit](https://user-images.githubusercontent.com/73630609/161752488-867dc8a9-4e0d-4fd0-9bbb-993ffbbc86fd.jpg)

**Comment by node3112** [comment]
lol ofc

**Comment by NathanW-05** [comment]
Where ian and arzi at? say i said "fuck you" if they never see the thread, i gotta go do class work

**Comment by node3112** [comment]
ight
